# Generated by Django 4.0 on 2023-01-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
    ]
