# Generated by Django 4.0 on 2023-01-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
