# Generated by Django 4.0 on 2023-01-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_django', '0003_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
